src/Entity/Zakazchiki.php
<?php

namespace App\Entity;

use App\Repository\ZakazchikiRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ZakazchikiRepository::class)
 */
class Zakazchiki
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Score;

    /**
     * @ORM\OneToMany(targetEntity=Zakazi::class, mappedBy="Zakazchik")
     */
    private $Code;

    public function __construct()
    {
        $this->Code = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getScore(): ?string
    {
        return $this->Score;
    }

    public function setScore(string $Score): self
    {
        $this->Score = $Score;

        return $this;
    }

    /**
     * @return Collection|Zakazi[]
     */
    public function getCode(): Collection
    {
        return $this->Code;
    }

    public function addCode(Zakazi $code): self
    {
        if (!$this->Code->contains($code)) {
            $this->Code[] = $code;
            $code->setZakazchik($this);
        }

        return $this;
    }

    public function removeCode(Zakazi $code): self
    {
        if ($this->Code->removeElement($code)) {
            // set the owning side to null (unless already changed)
            if ($code->getZakazchik() === $this) {
                $code->setZakazchik(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getName();
    }
}

src/Entity/Zakazi.php
<?php

namespace App\Entity;

use App\Repository\ZakaziRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ZakaziRepository::class)
 */
class Zakazi
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Amount;

    /**
     * @ORM\ManyToOne(targetEntity=Tovari::class, inversedBy="Code")
     */
    private $Tovar;

    /**
     * @ORM\ManyToOne(targetEntity=Zakazchiki::class, inversedBy="Code")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Zakazchik;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTovar(): ?Tovari
    {
        return $this->Tovar;
    }

    public function setTovar(?Tovari $Tovar): self
    {
        $this->Tovar = $Tovar;

        return $this;
    }

    public function getZakazchik(): ?Zakazchiki
    {
        return $this->Zakazchik;
    }

    public function setZakazchik(?Zakazchiki $Zakazchik): self
    {
        $this->Zakazchik = $Zakazchik;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->Amount;
    }

    public function setAmount(int $Amount): self
    {
        $this->Amount = $Amount;

        return $this;
    }

    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getId().':'.$this->getTovar().":".$this->getZakazchik();
    }
}

src/Form/ZakazchikiType.php
<?php

namespace App\Form;

use App\Entity\Zakazchiki;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ZakazchikiType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('Score')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Zakazchiki::class,
        ]);
    }
}

src/Controller/ZakazchikiController.php
<?php

namespace App\Controller;

use App\Entity\Zakazchiki;
use App\Entity\Zakazi;
use App\Form\ZakazchikiType;
use App\Repository\ZakazchikiRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Webmozart\Assert\Tests\StaticAnalysis\string;

/**
 * @Route("/zakazchiki")
 */
class ZakazchikiController extends AbstractController
{
    /**
     * @Route("/", name="zakazchiki_index", methods={"GET"})
     */
    public function index(ZakazchikiRepository $zakazchikiRepository): Response
    {
        return $this->render('zakazchiki/index.html.twig', [
            'zakazchikis' => $zakazchikiRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="zakazchiki_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $zakazchiki = new Zakazchiki();
        $form = $this->createForm(ZakazchikiType::class, $zakazchiki);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($zakazchiki);
            $entityManager->flush();

            return $this->redirectToRoute('zakazchiki_index');
        }

        return $this->render('zakazchiki/new.html.twig', [
            'zakazchiki' => $zakazchiki,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Request $request
     *
     * @return Response
     *
     * @Route("/otchet",name="otchet",methods={"GET"})
     */
    public function otchet(ZakazchikiRepository $zakazchikiRepository,Request $request):Response
    {
        $name = $request->query->get('name');
        $repository = $this->getDoctrine()->getRepository(Zakazi::class);
        return $this -> render('zakazchiki/otchet.html.twig',[
            'zakazis' => $repository -> findtoby ($zakazchikiRepository->findoneBy(['Name'=>$name])), 'string' => $name
        ]);
    }

    /**
     * @Route("/{id}", name="zakazchiki_show", methods={"GET"})
     */
    public function show(Zakazchiki $zakazchiki): Response
    {
        return $this->render('zakazchiki/show.html.twig', [
            'zakazchiki' => $zakazchiki,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="zakazchiki_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Zakazchiki $zakazchiki): Response
    {
        $form = $this->createForm(ZakazchikiType::class, $zakazchiki);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('zakazchiki_index');
        }

        return $this->render('zakazchiki/edit.html.twig', [
            'zakazchiki' => $zakazchiki,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="zakazchiki_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Zakazchiki $zakazchiki): Response
    {
        if ($this->isCsrfTokenValid('delete'.$zakazchiki->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($zakazchiki);
            $entityManager->flush();
        }

        return $this->redirectToRoute('zakazchiki_index');
    }
}

templates/zakazchiki/_delete_form.html.twig
<form method="post" action="{{ path('zakazchiki_delete', {'id': zakazchiki.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ zakazchiki.id) }}">
    <button class="btn">Delete</button>
</form>

templates/zakazchiki/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/zakazchiki/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Zakazchiki{% endblock %}

{% block body %}
    <h1>Edit Zakazchiki</h1>

    {{ include('zakazchiki/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('zakazchiki_index') }}">back to list</a>

    {{ include('zakazchiki/_delete_form.html.twig') }}
{% endblock %}

templates/zakazchiki/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Zakazchiki index{% endblock %}

{% block body %}
    <h1>Zakazchiki</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Score</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for zakazchiki in zakazchikis %}
            <tr>
                <td>{{ zakazchiki.id }}</td>
                <td>{{ zakazchiki.Name }}</td>
                <td>{{ zakazchiki.Score }}</td>
                <td>
                    <a href="{{ path('zakazchiki_show', {'id': zakazchiki.id}) }}">show</a>
                    <a href="{{ path('zakazchiki_edit', {'id': zakazchiki.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('zakazchiki_new') }}">Create new</a>

    <h2> Otchet </h2>
    <form action="{{ url('otchet') }}" method="get">
        <p><input name="name" type="text"></p>
        <p><input type="submit"></p>
    </form>
{% endblock %}

templates/zakazchiki/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Zakazchiki{% endblock %}

{% block body %}
    <h1>Create new Zakazchiki</h1>

    {{ include('zakazchiki/_form.html.twig') }}

    <a href="{{ path('zakazchiki_index') }}">back to list</a>
{% endblock %}

templates/zakazchiki/otchet.html.twig
{% extends 'base.html.twig' %}

{% block title %}Zakazi index{% endblock %}

{% block body %}
    <h1>Zakazi {{ string }}</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Tovar</th>
            <th>Amount</th> 
        </tr>
        </thead>
        <tbody>
        {% for zakazi in zakazis %}
            <tr>
                <td>{{ zakazi.id }}</td>
                <td>{{ zakazi.tovar }}</td>
                <td>{{ zakazi.amount }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="2">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/zakazchiki/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Zakazchiki{% endblock %}

{% block body %}
    <h1>Zakazchiki</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ zakazchiki.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ zakazchiki.Name }}</td>
            </tr>
            <tr>
                <th>Score</th>
                <td>{{ zakazchiki.Score }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('zakazchiki_index') }}">back to list</a>

    <a href="{{ path('zakazchiki_edit', {'id': zakazchiki.id}) }}">edit</a>

    {{ include('zakazchiki/_delete_form.html.twig') }}
{% endblock %}